language: cpp
dist: trusty

# 1. make sure travis client installed :
#.     https://github.com/travis-ci/travis.rb#installation
# 2. generate new token repo_public in github
# 3. add the 3 following lines with the command :
#      echo GH_TOKEN=token_generated_by_github | travis encrypt --add
env:
  global:
    - secure: GElPsvm52XhOLps6y+q3icvhYZDPLE7U8SJPpFvWDnTPKm7luj4EaHyMHIjG8pNP9HUstt/3IvXL7uoghVupPFi5BO9EDfyDpsDqVQqPQCla3FxM0iOdrw3Qmw3b0LKQ/fTBoUpcX4iedt/YlJVRy5+6h0WnW4il64y9MQhjAy/a7UM86XtF/phROq6wvs3uFvWCc3Lx49kE6T9XvD/TQVBgvDHSs5kawb55hAwZt8cp6cGvGrQQydJKLi9gg9ZP+9ts79emQjjSonJCkFGK9USqyek3i7xrPmjMFOMCB2M0Uh0ChXjVT3iegPvJhNWM3IEICmvqSrSVNGdXzvX5Oo24hd7jxXZNahiil4m9OYo4JaIzHodbvmM7q98rZVS0S1VjXQ6nUOAe2Z0hr4EXe2Qi3PTycsUeYLtb8frilPqsvqjTXoy+CSVAkAzHXYKZILap/YRreTNhR3I8sJEPhMrzy9mWHvQkQ+xSA0hYi6BnGUZ+NGpruvNkFp1cAxE244Cvj8QCBfadbUTTOYatg+TxKl2auIXCA92WwF0vpee/cn8Vb9ny6YtvnticX/V6h79aO9DrFrO1RCah4Czq/ZjARCPeS+56oi1/YFDeUR76/sp9vUIQRqXW8vN/3wkNKsuKr5E/gkWp9L7D/usOUCGXksNmCHfNNt0ubEsh7wM=

addons:
  apt:
    sources:
      - llvm-toolchain-trusty-3.9
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.9
      - g++-6
      - gcc-6
      - libgtkmm-3.0-dev
      - libssl-dev
      - uuid-dev
      - doxygen

before_script: scripts/travis/install_3rd_parties.sh

matrix:
  include:  
    - env: TEST="Format"
      os: linux
      script: scripts/travis/format.sh

    - env: TEST="Git check"
      os: linux
      script: scripts/travis/git_check.sh

# Too long : The job exceeded the maximum time limit for jobs, and has been terminated.
#    - env: TEST="Check"
#      os: linux
#      script: scripts/travis/check.sh

#    - env: TEST="Check Switch"
#      os: linux
#      script: scripts/travis/check_switch.sh

# Too long : The job exceeded the maximum time limit for jobs, and has been terminated.
#    - env: TEST="Check Switch.Core"
#      os: linux
#      script: scripts/travis/check_switch_core.sh

    - env: TEST="Check Switch.System"
      os: linux
      script: scripts/travis/check_switch_system.sh

    - env: TEST="Check Switch.System.Core"
      os: linux
      script: scripts/travis/check_switch_system_core.sh

    - env: TEST="Check Switch.System.Drawing"
      os: linux
      script: scripts/travis/check_switch_system_drawing.sh

    - env: TEST="Check Switch.System.ServiceModel"
      os: linux
      script: scripts/travis/check_switch_system_servicemodel.sh

    - env: TEST="Check Switch.System.Windows.Forms"
      os: linux
      script: scripts/travis/check_switch_system_windows_forms.sh

    - env: TEST="Check Switch.TUnit.Core"
      os: linux
      script: scripts/travis/check_switch_tunit_core.sh

    - env: TEST="Check Switch.TUnit.Framework"
      os: linux
      script: scripts/travis/check_switch_tunit_framework.sh

    - env: TEST="Check Switch.TUnit.Main"
      os: linux
      script: scripts/travis/check_switch_tunit_main.sh

    - env: TEST="Generate reference guide"
      os: linux
      script: scripts/travis/generate_reference_guide.sh

    - env: TEST="Build on Linux"
      os: linux
      script: scripts/travis/build_linux.sh

    - env: TEST="Build on macOS"
      os: osx
      osx_image: xcode9.1
      script: scripts/travis/build_macos.sh
      after_success: scripts/travis/publish_to_codecov.sh

#    - env: TEST="Google Address Sanitize"
#      os: osx
#      osx_image: xcode9.1
#      script: scripts/travis/build_macos_with_asan.sh

#    - env: TEST="Google Thread Sanitizer"
#      os: osx
#      osx_image: xcode9.1
#      script: scripts/travis/build_macos_with_tsan.sh

#    - env: TEST="Google Undefined Sanitizer"
#      os: osx
#      osx_image: xcode9.1
#      script: scripts/travis/build_macos_with_usan.sh
