#include <Switch/Switch>

using namespace System;
using namespace System::Drawing;

namespace Examples {
  class Program {
  public:
    // The main entry point for the application.
    static void Main() {
      Console::WriteLine("GenericMonospace : \"{0}\"", FontFamily::GenericMonospace().Name);
      Console::WriteLine("GenericSansSerif : \"{0}\"", FontFamily::GenericSansSerif().Name);
      Console::WriteLine("GenericSerif : \"{0}\"", FontFamily::GenericSerif().Name);
      Console::WriteLine("Families : {0}", FontFamily::Families().Length);
      for (System::Drawing::FontFamily fontFamily : System::Drawing::FontFamily::Families())
        Console::WriteLine("  fontFamily = \"{0}\"", fontFamily.Name);
    }
  };
}

startup_(Examples::Program);

// This code can produces the following output if you run on macOS:
//
// GenericMonospace : "Courier"
// GenericSansSerif : "Helvetica"
// GenericSerif : "Times"
// Families : 188
//   fontFamily = "Al Bayan"
//   fontFamily = "Al Nile"
//   fontFamily = "Al Tarikh"
//   fontFamily = "American Typewriter"
//   fontFamily = "Andale Mono"
//   fontFamily = "Apple Braille"
//   fontFamily = "Apple Chancery"
//   fontFamily = "Apple Color Emoji"
//   fontFamily = "Apple SD Gothic Neo"
//   fontFamily = "Apple Symbols"
//   fontFamily = "AppleGothic"
//   fontFamily = "AppleMyungjo"
//   fontFamily = "Arial"
//   fontFamily = "Arial Black"
//   fontFamily = "Arial Hebrew"
//   fontFamily = "Arial Hebrew Scholar"
//   fontFamily = "Arial Narrow"
//   fontFamily = "Arial Rounded MT Bold"
//   fontFamily = "Arial Unicode MS"
//   fontFamily = "Athelas"
//   fontFamily = "Avenir"
//   fontFamily = "Avenir Next"
//   fontFamily = "Avenir Next Condensed"
//   fontFamily = "Ayuthaya"
//   fontFamily = "Baghdad"
//   fontFamily = "Bangla MN"
//   fontFamily = "Bangla Sangam MN"
//   fontFamily = "Baskerville"
//   fontFamily = "Beirut"
//   fontFamily = "Big Caslon"
//   fontFamily = "Bodoni 72"
//   fontFamily = "Bodoni 72 Oldstyle"
//   fontFamily = "Bodoni 72 Smallcaps"
//   fontFamily = "Bodoni Ornaments"
//   fontFamily = "Bradley Hand"
//   fontFamily = "Brush Script MT"
//   fontFamily = "Chalkboard"
//   fontFamily = "Chalkboard SE"
//   fontFamily = "Chalkduster"
//   fontFamily = "Charter"
//   fontFamily = "Cochin"
//   fontFamily = "Comic Sans MS"
//   fontFamily = "Copperplate"
//   fontFamily = "Corsiva Hebrew"
//   fontFamily = "Courier"
//   fontFamily = "Courier New"
//   fontFamily = "Damascus"
//   fontFamily = "DecoType Naskh"
//   fontFamily = "Devanagari MT"
//   fontFamily = "Devanagari Sangam MN"
//   fontFamily = "Didot"
//   fontFamily = "DIN Alternate"
//   fontFamily = "DIN Condensed"
//   fontFamily = "Diwan Kufi"
//   fontFamily = "Diwan Thuluth"
//   fontFamily = "Euphemia UCAS"
//   fontFamily = "Farah"
//   fontFamily = "Farisi"
//   fontFamily = "Futura"
//   fontFamily = "GB18030 Bitmap"
//   fontFamily = "Geeza Pro"
//   fontFamily = "Geneva"
//   fontFamily = "Georgia"
//   fontFamily = "Gill Sans"
//   fontFamily = "Gujarati MT"
//   fontFamily = "Gujarati Sangam MN"
//   fontFamily = "Gurmukhi MN"
//   fontFamily = "Gurmukhi MT"
//   fontFamily = "Gurmukhi Sangam MN"
//   fontFamily = "Heiti SC"
//   fontFamily = "Heiti TC"
//   fontFamily = "Helvetica"
//   fontFamily = "Helvetica Neue"
//   fontFamily = "Herculanum"
//   fontFamily = "Hiragino Kaku Gothic Pro"
//   fontFamily = "Hiragino Kaku Gothic ProN"
//   fontFamily = "Hiragino Kaku Gothic Std"
//   fontFamily = "Hiragino Kaku Gothic StdN"
//   fontFamily = "Hiragino Maru Gothic Pro"
//   fontFamily = "Hiragino Maru Gothic ProN"
//   fontFamily = "Hiragino Mincho Pro"
//   fontFamily = "Hiragino Mincho ProN"
//   fontFamily = "Hiragino Sans"
//   fontFamily = "Hiragino Sans GB"
//   fontFamily = "Hoefler Text"
//   fontFamily = "Impact"
//   fontFamily = "InaiMathi"
//   fontFamily = "Iowan Old Style"
//   fontFamily = "ITF Devanagari"
//   fontFamily = "ITF Devanagari Marathi"
//   fontFamily = "Kailasa"
//   fontFamily = "Kannada MN"
//   fontFamily = "Kannada Sangam MN"
//   fontFamily = "Kefa"
//   fontFamily = "Khmer MN"
//   fontFamily = "Khmer Sangam MN"
//   fontFamily = "Kohinoor Bangla"
//   fontFamily = "Kohinoor Devanagari"
//   fontFamily = "Kohinoor Telugu"
//   fontFamily = "Kokonor"
//   fontFamily = "Krungthep"
//   fontFamily = "KufiStandardGK"
//   fontFamily = "Lao MN"
//   fontFamily = "Lao Sangam MN"
//   fontFamily = "Lucida Grande"
//   fontFamily = "Luminari"
//   fontFamily = "Malayalam MN"
//   fontFamily = "Malayalam Sangam MN"
//   fontFamily = "Marion"
//   fontFamily = "Marker Felt"
//   fontFamily = "Menlo"
//   fontFamily = "Microsoft Sans Serif"
//   fontFamily = "Mishafi"
//   fontFamily = "Mishafi Gold"
//   fontFamily = "Monaco"
//   fontFamily = "Mshtakan"
//   fontFamily = "Muna"
//   fontFamily = "Myanmar MN"
//   fontFamily = "Myanmar Sangam MN"
//   fontFamily = "Nadeem"
//   fontFamily = "New Peninim MT"
//   fontFamily = "Noteworthy"
//   fontFamily = "Noto Nastaliq Urdu"
//   fontFamily = "Optima"
//   fontFamily = "Oriya MN"
//   fontFamily = "Oriya Sangam MN"
//   fontFamily = "Palatino"
//   fontFamily = "Papyrus"
//   fontFamily = "Phosphate"
//   fontFamily = "PingFang HK"
//   fontFamily = "PingFang SC"
//   fontFamily = "PingFang TC"
//   fontFamily = "Plantagenet Cherokee"
//   fontFamily = "PT Mono"
//   fontFamily = "PT Sans"
//   fontFamily = "PT Sans Caption"
//   fontFamily = "PT Sans Narrow"
//   fontFamily = "PT Serif"
//   fontFamily = "PT Serif Caption"
//   fontFamily = "Raanana"
//   fontFamily = "Sana"
//   fontFamily = "Sathu"
//   fontFamily = "Savoye LET"
//   fontFamily = "Seravek"
//   fontFamily = "Shree Devanagari 714"
//   fontFamily = "SignPainter"
//   fontFamily = "Silom"
//   fontFamily = "Sinhala MN"
//   fontFamily = "Sinhala Sangam MN"
//   fontFamily = "Skia"
//   fontFamily = "Snell Roundhand"
//   fontFamily = "Songti SC"
//   fontFamily = "Songti TC"
//   fontFamily = "STIXGeneral"
//   fontFamily = "STIXIntegralsD"
//   fontFamily = "STIXIntegralsSm"
//   fontFamily = "STIXIntegralsUp"
//   fontFamily = "STIXIntegralsUpD"
//   fontFamily = "STIXIntegralsUpSm"
//   fontFamily = "STIXNonUnicode"
//   fontFamily = "STIXSizeFiveSym"
//   fontFamily = "STIXSizeFourSym"
//   fontFamily = "STIXSizeOneSym"
//   fontFamily = "STIXSizeThreeSym"
//   fontFamily = "STIXSizeTwoSym"
//   fontFamily = "STIXVariants"
//   fontFamily = "STSong"
//   fontFamily = "Sukhumvit Set"
//   fontFamily = "Superclarendon"
//   fontFamily = "Symbol"
//   fontFamily = "Tahoma"
//   fontFamily = "Tamil MN"
//   fontFamily = "Tamil Sangam MN"
//   fontFamily = "Telugu MN"
//   fontFamily = "Telugu Sangam MN"
//   fontFamily = "Thonburi"
//   fontFamily = "Times"
//   fontFamily = "Times New Roman"
//   fontFamily = "Trattatello"
//   fontFamily = "Trebuchet MS"
//   fontFamily = "Verdana"
//   fontFamily = "Waseem"
//   fontFamily = "Webdings"
//   fontFamily = "Wingdings"
//   fontFamily = "Wingdings 2"
//   fontFamily = "Wingdings 3"
//   fontFamily = "Zapf Dingbats"
//   fontFamily = "Zapfino"
